# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    env:
      BOOST_IO: 0
      STATIC: 1
      BGEN_VERSION: v1.1.7
      LIB_INSTALL: g++ libgomp1 make python3 zlib1g-dev wget
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prep GCC install
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update

      - name: Apt packages
        run: sudo apt install -y --no-install-recommends ${LIB_INSTALL}

      - name: Cache Bgen
        id: bgen-cache
        uses: actions/cache@v3
        with:
          path: bgen.tgz
          key: ${{ runner.os }}-bgen

      - name: Download Bgen if not cached
        if: steps.bgen-cache.outputs.cache-hit != 'true'
        run: |
          wget -O bgen.tgz "http://code.enkre.net/bgen/tarball/release/${BGEN_VERSION}"
      - name: Install Bgen
        run: |
          tar xzf bgen.tgz
          pushd ${BGEN_VERSION}
          python3 waf configure
          python3 waf -v
          popd
      - name: Build
        run: make BGEN_PATH=./${BGEN_VERSION} HAS_BOOST_IOSTREAM=$BOOST_IO STATIC=$STATIC all

      - name: Test
        run: ./regenie --help
